### ISSUE TITLE
Merge all DSDL repositories

### ISSUE THREAD

**Issue by antoinealb** [cvra/motor-control-uavcan-dsdl#5]
I suggest creating a single repository to hold all of our DSDL definitions. It would make more sense as in the end all the equipment will be connected on a single bus.

@SyrianSpock @nuft @Stapelzeiger  what do you guys think ?

**Comment by msplr** [comment]
I would prefer moving all datatype definitions directly to the projects' main repositories. No submodules.

**Comment by msplr** [comment]
My main point is that changing some datatype in the comm stack should require less steps.
As it is now, we have to modify 3 different repositories for every change.

**Comment by antoinealb** [comment]
So put everything in `robot-software` ?

**Comment by msplr** [comment]
> So put everything in robot-software ?

Yes, this also means moving `motor-control-firmware` into `robot-software`.

**Comment by antoinealb** [comment]
I agree that this would be the best option.

**Comment by Stapelzeiger** [comment]
I also agree with @nuft. I guess the same would apply for other boards, like the IO-board for example.

**Comment by SyrianSpock** [comment]
[Solved here](https://github.com/cvra/robot-software/pull/12)
